# This section provides information about the source, such as name and contact
# information.
# 
Source:
  name: 
  email: 

# This section provides information about all collections provided by the 
# source.
# 
Collections:
  
# This section contains information about a single collection.
# 

# Required directory name of the collection.
# 
- DirectoryName: 
   
  # Required MOL metadata (http://goo.gl/98r46)
  #  
  Required:
    absenceReliability: 
    accessrights: 
    bibliographiccitation: 
    breedingdomain: 
    contact: 
    coverage: 
    creator: 
    date: 
    description: 
    email: 
    eventdate: 
    nonbreedingdomain: 
    presencedefault: 
    publisher: 
    samplingprotocol: 
    scientificname: 
    source: 
    subject: 
    taxonomiccoverage: 
    title: 
    verbatimsrs: 

  # Optional MoL metadata (http://goo.gl/98r46)
  #
  Optional:
    accessright: 
    basemaps: 
    contributor: 
    enddateaccuracy: 
    format: 
    identifier: 
    language: 
    layertype: 
    mapcount: 
    maxregionsperspecies: 
    maxx: 
    maxy: 
    medianregionsperspecies: 
    minregionsperspecies: 
    minx: 
    miny: 
    relation: 
    rights: 
    startdateaccuracy: 
    surveyintervals: 
    taxonomy: 
    type: 

  # Mappings between collection DBF fields and MoL DBF fields: (http://goo.gl/UkzJW)
  # Note: Field names are case-sensitive.
  #
  DBFMapping:

    # Required MoL DBF fields 
    #
    Required:
      areaid: 
      bibliographiccitation: 
      polygonid: 
      polygonname: 
      scientificname: 

    # Optional MoL DBF fields
    #
    Optional:
      abundance: 
      abundancecomment: 
      abundancemakeup: 
      abundancemethod: 
      abundancesurveyarea: 
      abundanceunits: 
      areaname: 
      contributor: 
      dateend: 
      datestart: 
      distributioncomment: 
      dynamicproperties: 
      establishmentmeans: 
      infraspecificepithet: 
      later: 
      measurementcomment: 
      measurementmethod: 
      occurrencestatus: 
      population: 
      seasonality: 
      taxonid: 
      taxonremarks: 
